### ISSUE TITLE
pass debounce delay as an option

### ISSUE THREAD

**Issue by axyz** [sylvesteraswin/react-attach-handler#1]
https://github.com/sylvesteraswin/react-attach-handler/blob/master/src/AttachHandler.jsx#L52

should not be hardcoded, but be a parameter with a default.

**Comment by sylvesteraswin** [comment]
This is fixed in this PR https://github.com/sylvesteraswin/react-attach-handler/commit/4abaf16a2fcb57dcb66dbcadc11f0edc43f9632f
